### ISSUE TITLE
unfair comparison: baseline vs i-mix

### ISSUE THREAD

**Issue by kevinbro96** [kibok90/imix#5]
In run.sh, i-mix trains 2000 epochs while baseline trains 1000 epochs.
Is this a unfair comparison?

**Comment by kibok90** [comment]
No, all comparisons are fair. We experimented 0.2k, 0.5k, 1k, 2k (and 4k for some cases) epochs for all methods and reported the best performance. So, baseline @ 2k epochs is worse than baseline @ 1k epochs in that case.
Please also refer to Figure 1 in the paper.
