### ISSUE TITLE
Can't find "folder" package

### ISSUE THREAD

**Issue by AfrinaVT** [kibok90/imix#9]
Hi, 
I can see that you imported a package named "folder" for loading the imagenet dataset. When I run the code it gives an error saying there is no package named folder. Can you tell me where to get the folder package? I am attaching the image for reference. 
![image](https://github.com/kibok90/imix/assets/66439242/f291cfc9-41b6-4d6d-8439-072ee2b50dbb)

**Comment by kibok90** [comment]
It is a customized version of `torchvision.dataset.folder` to adjust the number of data and classes with additional arguments for some ablation studies in the paper. I just uploaded the code I used for the paper. Or, you can comment out those two lines and uncomment the line above to use the original torchvision code.
<img width="677" alt="image" src="https://github.com/kibok90/imix/assets/17054886/75f1071b-c09a-43d8-9cb4-696319e9e4af">
